language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5
    - android-sdk-license-c81a61d9

jdk: oraclejdk8

install:
  - true

script:
  - ./gradlew clean build check

cache:
  directories:
    - $HOME/.m2